ANSIBLE_USER: kevin
GITHUB_ACCESS_TOKEN: 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
priv_key_path: /home/{{ ANSIBLE_USER }}/.ssh/id_rsa
pub_key_path: /home/{{ ANSIBLE_USER }}/.ssh/id_rsa.pub
GIT_REPO: git@github.com:kevinabruner/pi.git
GIT_BRANCH: main
APPLICATION: jarvisfest
netbox_dns: netbox.thejfk.ca
certs_dir: "/opt/certs"
keepalived_conf: "keepalived.conf"
keepalived_dir: "/etc/keepalived/"
INTERFACE: eth0   
internal_router: 251
dev1: 192.168.80.27
dev2: 192.168.80.28
internal_vip: 192.168.80.39
prod1: 192.168.80.25
prod2: 192.168.80.26
external_vip: 192.168.80.40
external_router: 261