name: Dev Server Workflow
on:
  push:
    branches:
      - dev

jobs:
  build-dev:    
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ dev2, dev1 ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Git Pull
        run: cd /var/www/html && git pull
        shell: bash
