name: CI

on:
  push:
    branches: [ dev ]

jobs:
  deployment:
    runs-on:
      -self-hosted
      [web-jarvisfest-dev]
    steps:
    - name: Test
      working-directory: /var/www/html
      shell: bash
      run: |
        # Define a Bash function to perform git pull
        
        cd /var/www/html
        git pull
