name: Dev Server Workflow
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: [self-hosted, dev]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Git Pull
        run: cd /var/www/html && git pull
        shell: bash
