name: CI

on:
  push:
    branches:
      - main 
      - dev

jobs:
  deployment:
    runs-on: self-hosted
    steps:
    - name: Test
      working-directory: /var/www/html
      shell: bash
      run: |
        # Define a Bash function to perform git pull
        
        cd /var/www/html
        git pull
