name: CI

on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: self-hosted
    steps:
    - name: Test
      working-directory: /var/www/html
      shell: cmd
      run: ${{ secrets.PULL }}
