name: Prod Server Workflow
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, prod]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Git Pull
        run: cd /var/www/html && git pull
        shell: bash
